background {
  monitor =
  path = $HOME/.config/wallpapers/night.png
  blur_passes = 1
}
general {
  no_fade_in = false
  grace = 0
  disable_loading_bar = true
}

input-field {
  monitor = DP-5
  hide_input = false
  fade_on_empty = false
  size = 250, 60
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  placeholder_text = <i>Password</i>
  position = 0, -120
  halign = center
  valign = center
}
